import "@assets/scss/bootstrap.scss";
import "@assets/scss/app.scss";
import "@assets/icons/font-icon.css";
import Head from "next/head";
import {ReactNode} from "react";
import {NextIntlClientProvider} from "next-intl";
import {LayoutProps} from "@helpers/interfaces";

export function generateViewport(): Record<string, string | number> {
    return {
        width: "device-width",
        initialScale: 1,
        userScalable: "no",
    };
}

export async function generateMetadata(): Promise<{
    title: string;
    description: string;
}> {
    return {
        title: "TopSilver",
        description: "Generated by TopSilver",
    };
}

export default function Layout({children}: LayoutProps) {
    return (
        <html lang="en">
            <Head>
                <title>TopSilver Front</title>

                <link rel="icon" href="/favicon.ico" />
            </Head>

            <body>
                <NextIntlClientProvider>
                    {children}
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
