
import "@assets/scss/bootstrap.scss";
import "@assets/scss/app.scss";
import "@assets/icons/font-icon.css";
import Head from "next/head";
import { ReactNode } from "react";

export function generateViewport(): Record<string, string | number> {
  return {
    width: "device-width",
    initialScale: 1,
    userScalable: "no",
  };
}

export async function generateMetadata(): Promise<{
  title: string;
  description: string;
}> {
  return {
    title: "Kalles - Clean, Versatile, Responsive Bootstrap 5 & Nextjs Theme",
    description: "Generated by Kalles",
  };
}

interface LayoutProps {
  children: ReactNode;
}

export default function Layout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <Head>
        <title>
          Kalles - Clean, Versatile, Responsive Bootstrap 5 & Nextjs Theme
        </title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>{children}</body>
    </html>
  );
}
